# deno-fmt-ignore-file
name: check
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: hooks/pre-commit
